SHOW_SPEC_INFO = False
SHOW_KEY_INFO = False

AGGRESIVENESS = 20

# TYPE OF GENERIC ALGORITHM

FOLLOW_THE_KING = True
TOP_CARS_TO_PARENTS = True
KING_AS_A_PARENT = False
TOP_PERCENT = 15

MIX_GENRE = not FOLLOW_THE_KING and not TOP_CARS_TO_PARENTS and not KING_AS_A_PARENT
MIX_ORDER = [1, 1, 1]  # [FOLLOW_THE_KING, TOP_CARS_TO_PARENTS, KING_AS_A_PARENT, FOLLOW_THE_KING, ... ]
START_IDX_MIX_GENRE = 0
GENRES = len(MIX_ORDER)
